# Generated by Django 5.2.8 on 2026-02-26 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('vibe', models.CharField(choices=[('chill', 'Chill'), ('active', 'Active'), ('social', 'Social'), ('fun', 'Fun'), ('productive', 'Productive')], default='chill', max_length=20)),
                ('max_people', models.PositiveIntegerField(default=5)),
                ('post_to_campus_board', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sidequests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_datetime'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, help_text='User bio/description', max_length=500)),
                ('major', models.CharField(blank=True, help_text='Major/field of study', max_length=100)),
                ('class_year', models.CharField(blank=True, help_text="Class year (e.g., 'Class of '27')", max_length=50)),
                ('profile_picture', models.URLField(blank=True, help_text='URL to profile picture', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friends', models.ManyToManyField(blank=True, to='api.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='SidequestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('going', 'Going'), ('declined', 'Declined')], default='going', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('sidequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.sidequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidequest_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('sidequest', 'user')},
            },
        ),
    ]
