# Generated by Django 5.2.8 on 2026-02-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text="Display name shown on profile (e.g. 'Noah')", max_length=100),
        ),
    ]
