# Generated by Django 5.2.7 on 2025-10-15 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-start_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='week_number',
        ),
        migrations.AddField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
