# Generated by Django 5.2.7 on 2025-11-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_challenge_options_remove_challenge_week_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='file',
            field=models.URLField(max_length=500),
        ),
    ]
