# Generated by Django 5.2.8 on 2026-03-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidequest',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
