# Generated by Django 5.2.7 on 2025-11-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_challenge_options_remove_challenge_week_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='User bio/description', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_year',
            field=models.CharField(blank=True, help_text="Class year (e.g., 'Class of '27')", max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, help_text='Major/field of study', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='URL to profile picture', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
