# Generated by Django 5.2.8 on 2026-03-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sidequest_end_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text="List of user interests (e.g., [{'emoji': '🏀', 'label': 'basketball'}])"),
        ),
    ]
