# Generated by Django 5.2.8 on 2026-03-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidequest',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sidequestparticipant',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
