# Generated by Django 5.2.8 on 2025-11-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_bio_userprofile_class_year_and_more'),
        ('api', '0005_season'),
    ]

    operations = [
    ]
